### ISSUE TITLE
No such file or directory: 'trec_5500_trim.label'

### ISSUE THREAD

**Issue by davidlee321** [PurduePAML/TrojanNN#5]
Hi , I'm trying out the attitude section and encountered this error. Would be glad if you could assist.

```bash
$ python process_data.py GoogleNews-vectors-negative300.bin
loading data...
Traceback (most recent call last):
  File "process_data.py", line 130, in <module>
    revs, vocab = build_data_cv(data_folder, cv=10, clean_string=True)
  File "process_data.py", line 15, in build_data_cv
    with open(pos_file, "rb") as f:
IOError: [Errno 2] No such file or directory: 'trec_5500_trim.label'
```

**Comment by davidlee321** [comment]
[SOLVED] 
Run the `process_data.py` from `https://github.com/yoonkim/CNN_sentence`, not from this repository.
